"""Render an ASCII tree index of every URL each lab has scraped.

Reads <data>/<group>/<lab>/manifest.json and writes URL-INDEX.md at the root of the
repository that holds them, falling back to the data directory when there is none.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from urllib.parse import urlsplit

from euripontida_crawlee.config import get_settings
from euripontida_crawlee.versioning.vcs import repository_root


def _index_path(data: Path) -> Path:
    """The index belongs at the root of whatever repository holds the corpora."""
    root = repository_root(data)
    return (root or data) / 'URL-INDEX.md'


SETTINGS = get_settings()
DATA = SETTINGS.resolve(SETTINGS.data_dir)
OUT = _index_path(DATA)


class Node:
    __slots__ = ('children', 'count', 'failed', 'is_page')

    def __init__(self) -> None:
        self.children: dict[str, Node] = {}
        self.count = 0
        self.is_page = False
        self.failed = False


def segments(url: str) -> tuple[str, list[str]]:
    parts = urlsplit(url)
    path = [s for s in parts.path.split('/') if s]
    if not path:
        path = ['/']
    if parts.query:
        path[-1] = f'{path[-1]}?{parts.query}'
    return parts.netloc, path


def insert(root: Node, path: list[str], failed: bool) -> None:
    node = root
    for part in path:
        node.count += 1
        node = node.children.setdefault(part, Node())
    node.count += 1
    node.is_page = True
    node.failed = failed


def render(node: Node, prefix: str, lines: list[str]) -> None:
    dirs = sorted((k, v) for k, v in node.children.items() if v.children)
    leaves = sorted((k, v) for k, v in node.children.items() if not v.children)
    entries = dirs + leaves
    for index, (name, child) in enumerate(entries):
        last = index == len(entries) - 1
        elbow = '`-- ' if last else '|-- '
        if child.children:
            label = f'{name}/  ({child.count})'
            if child.is_page:
                label += ' *'
        else:
            label = name
        if child.failed:
            label += '  !'
        lines.append(prefix + elbow + label)
        if child.children:
            render(child, prefix + ('    ' if last else '|   '), lines)


def lab_tree(manifest: Path) -> tuple[int, int, list[str]]:
    pages = json.loads(manifest.read_text(encoding='utf-8'))['pages']
    hosts: dict[str, Node] = {}
    failures = 0
    for url, page in pages.items():
        host, path = segments(url)
        failed = page.get('status') != 'ok'
        failures += failed
        insert(hosts.setdefault(host, Node()), path, failed)
    lines: list[str] = []
    for host in sorted(hosts):
        lines.append(f'{host}/  ({hosts[host].count})')
        render(hosts[host], '', lines)
    return len(pages), failures, lines


def main() -> None:
    manifests = sorted(DATA.glob('*/*/manifest.json'))
    groups: dict[str, list[Path]] = {}
    for manifest in manifests:
        groups.setdefault(manifest.parent.parent.name, []).append(manifest)

    gw = max(len(g) for g in groups)
    lw = max(len(m.parent.name) for m in manifests)

    totals: Counter[str] = Counter()
    out: list[str] = []
    out.append('# URL index')
    out.append('')
    out.append("Every URL currently held by each lab's corpus, as an ASCII tree, one section per")
    out.append('lab. Generated by `scripts/url_tree.py` from the manifests on disk.')
    out.append('')
    out.append('Legend:')
    out.append('')
    out.append('- `name/  (N)` is a path prefix holding N scraped URLs')
    out.append('- `name` is a scraped URL')
    out.append('- `*` marks a prefix that is itself also scraped')
    out.append('- `!` marks a URL whose last fetch failed')
    out.append('')

    body: list[str] = []
    rule = f'    {"-" * gw}   {"-" * lw}   ----   ------'
    summary: list[str] = [f'    {"Group":<{gw}}   {"Lab":<{lw}}   URLs   Failed', rule]
    for group in sorted(groups):
        body.append(f'## {group}')
        body.append('')
        for manifest in groups[group]:
            lab = manifest.parent.name
            count, failures, lines = lab_tree(manifest)
            totals['urls'] += count
            totals['failed'] += failures
            summary.append(f'    {group:<{gw}}   {lab:<{lw}}   {count:>4}   {failures:>6}')
            body.append(f'### {lab}')
            body.append('')
            body.append(f'{count} URLs, {failures} failed.')
            body.append('')
            body.append('```text')
            body.extend(lines)
            body.append('```')
            body.append('')

    summary.append(rule)
    summary.append(f'    {"TOTAL":<{gw}}   {"":<{lw}}   {totals["urls"]:>4}   {totals["failed"]:>6}')

    out.append('## Summary')
    out.append('')
    out.extend(summary)
    out.append('')
    out.extend(body)

    OUT.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print(f'{OUT}: {totals["urls"]} URLs across {len(manifests)} labs, {totals["failed"]} failed')


if __name__ == '__main__':
    main()
